COLUMNS:
  batting_team: object
  bowling_team: object
  city: object
  runs_left: int64
  balls_left: int64
  wickets: int64
  total_runs_x: int64
  crr: float64
  rrr: float64
  result: int64
TARGET_COLUMN:
  name: result